### ISSUE TITLE
Gamewatch dumped attacklw4 script

### ISSUE THREAD

**Issue by BruhLookAtThis** [WuBoytH/SSBU-Dumped-Scripts#5]
Noticed two "COLLISION_SITUATION_MASK_G_d" didn't have an asterisk at the beginning like the rest of the COLLISION_SITUATION_MASK_s, that being missing seems to be why my script failed to compile. Adding them worked.

Are those intentionally missing? From your dumped script?

https://github.com/WuBoytH/SSBU-Dumped-Scripts/blob/main/smashline/lua2cpp_gamewatch/gamewatch/game/game_AttackLw4.txt

**Comment by WuBoytH** [comment]
It's a conversion error from skyline-acmd to smashline. Will fix.

**Comment by BruhLookAtThis** [comment]
one more thing, it says "collision_attr_noamal" instead or "normal" for two of em. Hasn't crashed my game but that doesn't look right

**Comment by WuBoytH** [comment]
That's actually how the vanilla script is, you can tell because when you hit someone with that hitbox in vanilla, no effects will play out.
I have fixed the original issue, will close.
