### ISSUE TITLE
lua2cpp_common and lua2cpp_item dumps

### ISSUE THREAD

**Issue by GarfQC** [WuBoytH/SSBU-Dumped-Scripts#6]
I'm noticing the lack of lua2cpp_common and lua2cpp_item dumps in here.

I get that dumping scripts is a hard task, but having dumps for those scripts in here would be great.
a lua2cpp_item script dump in particular would probably be a great tool for item-related code mods.

**Comment by WuBoytH** [comment]
It's been a while since this was opened but all item acmd was dumped a few months ago.
lua2cpp_common scripts are not worth dumping unless done by hand, as they are inherently not supported by smashline.
